# Generated by Django 4.2.15 on 2024-08-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeDesejos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadedesejos',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='listadedesejos',
            name='querometro',
        ),
        migrations.AlterField(
            model_name='listadedesejos',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Lista'),
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Presente')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Médio')),
                ('querometro', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Querômetro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link para o Produto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentes', to='listaDeDesejos.listadedesejos', verbose_name='Lista de Desejos')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
            },
        ),
    ]
