# Generated by Django 4.2.15 on 2024-08-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeDesejos', '0002_remove_listadedesejos_preco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadedesejos',
            old_name='descricao',
            new_name='descricao_lista',
        ),
        migrations.RenameField(
            model_name='presente',
            old_name='descricao',
            new_name='descricao_presente',
        ),
    ]
